on:
  pull_request:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml

name: Semgrep

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        id: semgrep
        run: |
          # Get the list of changed files in the pull request
          changed_files=$(jq -r '.pull_request.changed_files' $GITHUB_EVENT_PATH)

          # Run Semgrep only on the changed files
          output=$(semgrep --config=auto --json --metrics=off $changed_files)
          echo "$output" > semgrep_output.json
          echo "::set-output name=semgrep_output::$output"

      - name: Display Findings
        run: |
          cat semgrep_output.json

      - name: Format and Summarize Findings
        run: |
          jq -r '.results[] | "\(.file) - \(.start.line):\(.start.col) - \(.end.line):\(.end.col) [\(.check_id)] - \(.extra.message)"' semgrep_output.json
