on:
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
      - '**/*' # Adjust the paths as needed

name: Semgrep

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: get_changed_files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "::set-output name=files::$changed_files"

      - name: Run Semgrep on changed files
        id: semgrep
        run: |
          changed_files="${{ steps.get_changed_files.outputs.files }}"
          if [ -n "$changed_files" ]; then
            output=$(semgrep -f "$changed_files" --json)
          else
            output=$(semgrep scan --json)
          fi
          echo "$output" > semgrep_output.json
          echo "::set-output name=semgrep_output::$output"

      - name: Display Findings
        run: |
          cat semgrep_output.json

      - name: Format and Summarize Findings
        run: |
          jq -r '.results[] | "\(.file) - \(.start.line):\(.start.col) - \(.end.line):\(.end.col) [\(.check_id)] - \(.extra.message)"' semgrep_output.json
