on:
  pull_request: {}
  push:
    branches:
      - main
      - master
      
  schedule:
    - cron: '0 0 * * *'

name: Semgrep

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep
        run: |
          set -e
          semgrep ci || echo "Semgrep analysis failed. Check the logs for details."

      - name: Check Semgrep Results
        run: |
          semgrep_results=$(semgrep --json ci)
          if [[ $? -eq 0 ]]; then
            echo "Semgrep analysis succeeded."
          else
            echo "Semgrep analysis failed. Check the logs for details."
            echo "$semgrep_results"
            exit 1
          fi
