name: Combined Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Comment on Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node comment-on-pr.js

  semgrep:
    name: Semgrep
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Semgrep
        id: semgrep
        run: |
          output=$(semgrep ci --json)
          echo "$output" > semgrep_output.json

      - name: Display Findings
        run: |
          cat semgrep_output.json

      - name: Format and Summarize Findings
        id: summarize_findings
        run: |
          findings=$(jq -r '.results[] | "\(.file) - \(.start.line):\(.start.col) - \(.end.line):\(.end.col) [\(.check_id)] - \(.extra.message)"' semgrep_output.json)
          echo "$findings" > findings.txt
          echo "::set-output name=findings::$findings"

      - name: Check Findings and Run Command
        run: |
          findings=$(jq '.results | length' semgrep_output.json)
          if [ "$findings" -gt 0 ]; then
            echo "Findings found. Running semgrep --error"
            semgrep --error
          else
            echo "No findings. Skipping semgrep --error"
          fi
