on:
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml

name: Semgrep

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        id: semgrep
        run: |
          output=$(semgrep ci --json)
          echo "$output" > semgrep_output.json

      - name: Display Findings
        run: |
          cat semgrep_output.json

      - name: Format and Summarize Findings
        run: |
          jq -r '.results[] | "\(.file) - \(.start.line):\(.start.col) - \(.end.line):\(.end.col) [\(.check_id)] - \(.extra.message)"' semgrep_output.json

      - name: Check Findings and Run Command
        run: |
          findings=$(jq '.results | length' semgrep_output.json)
          if [ "$findings" -gt 0 ]; then
            echo "Findings found. Running semgrep --error"
            semgrep --error
          else
            echo "No findings. Skipping semgrep --error"
          fi
