on:
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml

name: Semgrep

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        id: semgrep
        run: |
          output=$(semgrep ci --json)
          echo "$output" > semgrep_output.json

      - name: Display Findings
        run: |
          cat semgrep_output.json

      - name: Format and Summarize Findings
        id: summarize_findings
        run: |
          findings=$(jq -r '.results[] | "\(.file) - \(.start.line):\(.start.col) - \(.end.line):\(.end.col) [\(.check_id)] - \(.extra.message)"' semgrep_output.json)
          echo "$findings" > findings.txt
          echo "::set-output name=findings::$findings"

  create_comment:
    needs: semgrep
    runs-on: ubuntu-20.04
    steps:
      - name: Create Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const findingsContent = require('fs').readFileSync('./findings.txt', 'utf-8');
            const context = github.context;

            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Semgrep Findings:\n' + findingsContent,
            });

      - name: Check Findings and Run Command
        if: always()
        run: |
          findings=$(cat findings.txt 2>/dev/null || echo "")
          if [ -n "$findings" ]; then
            echo "Findings found. Running semgrep --error"
            semgrep --error
          else
            echo "No findings. Skipping semgrep --error"
          fi
