on:
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml

name: Semgrep

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        id: semgrep
        run: |
          output=$(semgrep ci --json)
          echo "$output" > semgrep_output.json

      - name: Display Findings
        run: |
          cat semgrep_output.json

      - name: Comment on PR if findings exist
        id: pr_comment
        run: |
          findings=$(jq '.results | length' semgrep_output.json)
          if [ "$findings" -gt 0 ]; then
            echo "Findings found. Commenting on the PR."
            echo "Semgrep SAST Scan - Findings found. Check the details in the workflow run artifacts." > pr_comment.txt
          else
            echo "No findings. Skipping PR comment."
            echo "Semgrep SAST Scan - No findings." > pr_comment.txt
          fi
          echo "::set-output name=pr_comment_file_exists::True"
        continue-on-error: true

      - name: Upload PR comment
        uses: actions/upload-artifact@v2
        with:
          name: pr-comment
          path: pr_comment.txt
        if: steps.pr_comment.outputs.pr_comment_file_exists == 'True'
